package com.sadad.app;
import android.app.Instrumentation;
import android.content.Context;
import android.os.Bundle;
import android.os.SystemClock;
import android.provider.Settings;
import org.json.*;
import java.nio.charset.StandardCharsets;
import java.util.UUID;

/** اختبارات محلية على Android فعلي باستخدام Keystore وSQLite؛ ليست اختبارات خادم. */
public final class LedgerInstrumentation extends Instrumentation {
 private final JSONArray tests=new JSONArray();
 private Bundle arguments;
 private void check(String name,boolean condition)throws Exception{if(!condition)throw new AssertionError(name);tests.put(new JSONObject().put("name",name).put("status","passed"));}
 public void onCreate(Bundle args){super.onCreate(args);arguments=args;start();}
 public void onStart(){Bundle result=new Bundle();LedgerRepository repo=null;try{
  if(arguments!=null&&arguments.containsKey("mode")){liveMode(arguments.getString("mode"),result);return;}
  Context context=getTargetContext().createDeviceProtectedStorageContext();SessionStore session=new SessionStore(context);String user=UUID.randomUUID().toString();String jwt="e30."+InstallationKey.b64(new JSONObject().put("sub",user).toString().getBytes(StandardCharsets.UTF_8))+".local";
  session.save(new JSONObject().put("token","local-device-token").put("expiresAt",System.currentTimeMillis()+3600000).put("account",new JSONObject().put("id","-99")).put("auth",new JSONObject().put("accessToken",jwt).put("refreshToken","local-refresh-token").put("expiresAt",System.currentTimeMillis()+3600000)));
  repo=new LedgerRepository(context,session);String scope=repo.journal.scope,contact=UUID.randomUUID().toString(),debt=UUID.randomUUID().toString(),epoch=UUID.randomUUID().toString();
  repo.journal.metadata("installation",new JSONObject().put("generation",1).put("status","active"));
  JSONObject lease=new JSONObject().put("issuedAt",System.currentTimeMillis()).put("expiresAt",System.currentTimeMillis()+7*86400000L);
  repo.journal.metadata("lease",new JSONObject().put("payload",lease).put("elapsed",SystemClock.elapsedRealtime()).put("wall",System.currentTimeMillis()).put("boot",Settings.Global.getInt(context.getContentResolver(),"boot_count",-1)));
  JSONObject snapshot=new JSONObject().put("epoch",epoch).put("cursor",0).put("contacts",new JSONArray().put(new JSONObject().put("id",contact).put("name","اسم سري لا يظهر في SQLite").put("archived",false).put("version",1))).put("debts",new JSONArray().put(new JSONObject().put("id",debt).put("contact_id",contact).put("direction","receivable").put("amount_cents",50000))).put("payments",new JSONArray()).put("outcomes",new JSONArray()).put("reversals",new JSONArray()).put("adjustments",new JSONArray());
  repo.journal.merge(snapshot);JSONObject first=repo.add("payment.create",new JSONObject().put("debtId",debt).put("amountCents",10000).put("method","cash"));
  check("الرصيد يشمل دفعة معلقة ٥٠٠ ← ٤٠٠",repo.view().getJSONArray("debts").getJSONObject(0).getLong("remainingCents")==40000);
  repo.journal.close();repo=new LedgerRepository(context,session);check("الطابور يبقى بعد إغلاق قاعدة البيانات وإعادة فتحها",repo.journal.entries().length()==1);
  JSONObject sending=repo.journal.startSend(first.getJSONObject("command").getString("operationId"));boolean cancelled=false;try{repo.journal.cancel(first.getJSONObject("command").getString("operationId"));cancelled=true;}catch(IllegalArgumentException expected){}check("لا إلغاء بعد بدء الإرسال",!cancelled);
  repo.journal.state(sending,"uncertain","انقطاع الشبكة");repo.journal.merge(snapshot);check("نسخة خادم قديمة لا تمحو الأثر غير المؤكد",repo.view().getJSONArray("debts").getJSONObject(0).getLong("remainingCents")==40000);
  JSONObject receipt=new JSONObject().put("operationId",first.getJSONObject("command").getString("operationId")).put("status","accepted").put("sequence",1).put("epoch",epoch);
  sending.put("receipt",receipt);repo.journal.state(sending,"acknowledged","");check("الإيصال لا يزيل الإسقاط قبل وصول النسخة",repo.view().getJSONArray("debts").getJSONObject(0).getLong("remainingCents")==40000);
  snapshot.put("cursor",1).put("payments",new JSONArray().put(new JSONObject().put("id",first.getJSONObject("command").getString("entityId")).put("debt_id",debt).put("amount_cents",10000))).put("outcomes",new JSONArray().put(receipt));repo.journal.merge(snapshot);
  check("تأكيد الدفعة لا يخصم المبلغ مرتين",repo.view().getJSONArray("debts").getJSONObject(0).getLong("remainingCents")==40000);
  JSONObject rejected=repo.add("payment.create",new JSONObject().put("debtId",debt).put("amountCents",2000).put("method","cash"));repo.journal.state(rejected,"rejected","رفض نهائي");check("الرفض يزيل الإسقاط ويحفظ التفاصيل",repo.view().getJSONArray("debts").getJSONObject(0).getLong("remainingCents")==40000&&repo.journal.entries().length()==2);
  JSONObject queued=repo.add("payment.create",new JSONObject().put("debtId",debt).put("amountCents",10000).put("method","cash"));boolean exceeded=false;try{repo.add("payment.create",new JSONObject().put("debtId",debt).put("amountCents",30001).put("method","cash"));exceeded=true;}catch(IllegalArgumentException expected){}check("الدفعات المتكررة لا تتجاوز المتبقي المتوقع",!exceeded);repo.journal.cancel(queued.getJSONObject("command").getString("operationId"));check("الإلغاء غير المرسل محفوظ في التاريخ",repo.journal.entries().getJSONObject(2).getString("state").equals("cancelled"));
  JSONObject bundle=repo.journal.exportPlain();byte[] sealed=RecoveryCrypto.seal(bundle,"عبارة مرور قوية للتجربة ١٢٣".toCharArray());boolean wrong=false;try{RecoveryCrypto.open(sealed,"كلمة خاطئة لا تفتح الملف".toCharArray());wrong=true;}catch(Exception expected){}check("رفض عبارة مرور خاطئة",!wrong);JSONObject decoded=RecoveryCrypto.open(sealed,"عبارة مرور قوية للتجربة ١٢٣".toCharArray());repo.journal.importPlain(decoded);check("استيراد النسخة ذاتها لا يكرر العمليات",repo.journal.entries().length()==3);
  JSONObject tampered=new JSONObject(new String(sealed,StandardCharsets.UTF_8));byte[] cipher=InstallationKey.unb64(tampered.getString("data"));cipher[0]^=1;tampered.put("data",InstallationKey.b64(cipher));boolean allowed=false;try{RecoveryCrypto.open(tampered.toString().getBytes(StandardCharsets.UTF_8),"عبارة مرور قوية للتجربة ١٢٣".toCharArray());allowed=true;}catch(Exception expected){}check("رفض التلاعب بالملف المشفر",!allowed);
  allowed=false;try{RecoveryCrypto.open(java.util.Arrays.copyOf(sealed,sealed.length/2),"عبارة مرور قوية للتجربة ١٢٣".toCharArray());allowed=true;}catch(Exception expected){}check("رفض الملف المبتور دون تغيير الطابور",!allowed&&repo.journal.entries().length()==3);
  JSONObject wrongScope=new JSONObject(decoded.toString()).put("scope","مشروع آخر|متجر آخر|مستخدم آخر");allowed=false;try{repo.journal.importPlain(wrongScope);allowed=true;}catch(Exception expected){}check("رفض استرداد نطاق مختلف",!allowed);
  JSONObject person=repo.add("contact.create",new JSONObject().put("name","شخص معلق")),dependent=repo.add("debt.create",new JSONObject().put("contactId",person.getJSONObject("command").getString("entityId")).put("amountCents",100).put("direction","receivable"));allowed=false;try{repo.journal.cancel(person.getJSONObject("command").getString("operationId"));allowed=true;}catch(Exception expected){}check("منع إلغاء أصل له إدخال تابع",!allowed);repo.journal.cancel(dependent.getJSONObject("command").getString("operationId"));repo.journal.cancel(person.getJSONObject("command").getString("operationId"));
  JSONObject replacement=repo.add("payment.create",new JSONObject().put("debtId",debt).put("amountCents",1000).put("method","cash"),rejected.getJSONObject("command").getString("operationId"));check("مراجعة الرفض تولد رقمًا جديدًا مرتبطًا وتحفظ الأصل",!replacement.getJSONObject("command").getString("operationId").equals(rejected.getJSONObject("command").getString("operationId"))&&repo.journal.entries().getJSONObject(1).getString("state").equals("reviewed"));repo.journal.cancel(replacement.getJSONObject("command").getString("operationId"));
  JSONObject leaseSaved=repo.journal.metadata("lease");repo.journal.metadata("lease",new JSONObject(leaseSaved.toString()).put("wall",System.currentTimeMillis()+120000));check("إرجاع الساعة يمنع إضافات جديدة",!repo.canAddOffline());repo.journal.metadata("lease",new JSONObject(leaseSaved.toString()).put("boot",-2));check("تغير دورة الإقلاع يمنع تمديد الترخيص",!repo.canAddOffline());repo.journal.metadata("lease",leaseSaved);
  check("التصدير لا يحتوي رموز الدخول",!bundle.toString().contains("local-refresh-token")&&!bundle.toString().contains("local-device-token"));
  JSONObject restoreBundle=repo.journal.exportPlain();JSONObject unknown=new JSONObject(first.getJSONObject("command").toString()).put("operationId",UUID.randomUUID().toString()).put("entityId",UUID.randomUUID().toString());JSONObject unknownEntry=repo.journal.add(unknown);unknownEntry=repo.journal.startSend(unknown.getString("operationId"));repo.journal.state(unknownEntry,"uncertain","رد مفقود");JSONObject unsent=new JSONObject(unknown.toString()).put("operationId",UUID.randomUUID().toString()).put("entityId",UUID.randomUUID().toString());repo.journal.add(unsent);restoreBundle=repo.journal.exportPlain();
  Context restoreContext=new android.content.ContextWrapper(context){public android.database.sqlite.SQLiteDatabase openOrCreateDatabase(String name,int mode,android.database.sqlite.SQLiteDatabase.CursorFactory factory){return android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(new java.io.File(getFilesDir(),"restore-"+name),factory);}};
  EncryptedJournal restored=new EncryptedJournal(restoreContext,scope);restored.importPlain(restoreBundle);restored.importPlain(restoreBundle);JSONArray recoveredEntries=restored.entries();boolean allPreserved=recoveredEntries.length()==repo.journal.entries().length();for(int i=0;i<recoveredEntries.length();i++){JSONObject original=repo.journal.entries().getJSONObject(i),copy=recoveredEntries.getJSONObject(i);allPreserved&=copy.getString("wire").equals(original.getString("wire"));if(original.getString("state").equals("cancelled")||original.getString("state").equals("reviewed")||original.getString("state").equals("rejected"))allPreserved&=copy.getString("state").equals(original.getString("state"));else allPreserved&=copy.getString("state").equals("blocked");}check("استرداد جديد يحفظ أرقام ومحتوى كل الحالات بلا تكرار ويبقي المحتمل إرساله للمصالحة",allPreserved);restored.close();
  EncryptedJournal another=new EncryptedJournal(context,scope);String lock=repo.journal.acquire();check("نسختا المستودع تشتركان في قفل عامل واحد",lock!=null&&another.acquire()==null);repo.journal.release(lock);another.close();
  java.lang.reflect.Field field=EncryptedJournal.class.getDeclaredField("db");field.setAccessible(true);android.database.sqlite.SQLiteDatabase sql=(android.database.sqlite.SQLiteDatabase)field.get(repo.journal);long pageCount=android.database.DatabaseUtils.longForQuery(sql,"PRAGMA page_count",null),pageSize=android.database.DatabaseUtils.longForQuery(sql,"PRAGMA page_size",null);long previousMaximum=sql.getMaximumSize();sql.beginTransaction();try{sql.setMaximumSize(pageCount*pageSize);sql.setTransactionSuccessful();}finally{sql.endTransaction();}int beforeFailure=repo.journal.entries().length();boolean falselySaved=false;try{JSONObject huge=new JSONObject(unknown.toString()).put("operationId",UUID.randomUUID().toString());huge.getJSONObject("payload").put("note",new String(new char[1024*1024]).replace('\0','x'));repo.journal.add(huge);falselySaved=true;}catch(android.database.sqlite.SQLiteException expected){}finally{sql.beginTransaction();try{sql.setMaximumSize(previousMaximum);sql.setTransactionSuccessful();}finally{sql.endTransaction();}}check("فشل كتابة SQLite مضبوط لا يسجل نجاحًا أو إدخالًا جزئيًا",!falselySaved&&repo.journal.entries().length()==beforeFailure);
  repo.journal.metadata("lease",new JSONObject().put("payload",new JSONObject().put("issuedAt",0).put("expiresAt",1)).put("elapsed",SystemClock.elapsedRealtime()).put("wall",System.currentTimeMillis()).put("boot",Settings.Global.getInt(context.getContentResolver(),"boot_count",-1)));check("انتهاء الأيام السبعة يوقف الإضافة ويبقي القراءة",!repo.canAddOffline()&&repo.view().getJSONArray("contacts").length()==1);
  result.putString("evidence",new JSONObject().put("engine","Android Keystore + SQLite/WAL").put("leaseFixture","محلي للاختبار؛ فحص الترخيص الموقع منفصل").put("tests",tests).toString());finish(0,result);
 }catch(Throwable e){result.putString("failure",e.toString());result.putString("passedBeforeFailure",tests.toString());finish(1,result);}finally{if(repo!=null)repo.journal.close();}}
 private void liveMode(String mode,Bundle result)throws Exception{
  Context context=getTargetContext();SessionStore session=new SessionStore(context);LedgerRepository repo=null;
  try{
   if(mode.equals("ui")){android.app.Activity activity=startActivitySync(new android.content.Intent(context,LedgerActivity.class).addFlags(android.content.Intent.FLAG_ACTIVITY_NEW_TASK));java.util.concurrent.atomic.AtomicReference<String> dom=new java.util.concurrent.atomic.AtomicReference<>("");for(int attempt=0;attempt<20;attempt++){java.util.concurrent.CountDownLatch latch=new java.util.concurrent.CountDownLatch(1);runOnMainSync(()->{android.view.ViewGroup content=activity.findViewById(android.R.id.content);android.webkit.WebView web=(android.webkit.WebView)content.getChildAt(0);web.evaluateJavascript("JSON.stringify({rtl:document.documentElement.dir,people:document.querySelectorAll(\"#content .item\").length,mainVisible:!document.getElementById(\"main\").classList.contains(\"hidden\"),balance:document.getElementById(\"receivable\").textContent})",value->{dom.set(value);latch.countDown();});});latch.await(3,java.util.concurrent.TimeUnit.SECONDS);if(dom.get().contains("3560.00"))break;SystemClock.sleep(500);}JSONObject actual=new JSONObject(new org.json.JSONTokener(dom.get()).nextValue().toString());check("واجهة WebView تعرض ١٥ شخصًا والرصيد الحقيقي بالعربية",actual.getString("rtl").equals("rtl")&&actual.getInt("people")==15&&actual.getBoolean("mainVisible")&&actual.getString("balance").contains("3560.00"));runOnMainSync(activity::finish);}
   else if(mode.equals("login")){java.io.File fixture=new java.io.File(context.getFilesDir(),"test-login.json");JSONObject c=new JSONObject(new String(java.nio.file.Files.readAllBytes(fixture.toPath()),StandardCharsets.UTF_8));LedgerTransport transport=new LedgerTransport(session,new InstallationKey(context));JSONObject login=transport.legacy("mobile/login",new JSONObject().put("username",c.getString("username")).put("password",c.getString("password")).put("deviceId",new InstallationKey(context).id()).put("deviceName","محاكي تحقق سدد v3").put("staffName","صاحب المتجر"),false);session.save(login);if(!fixture.delete())throw new java.io.IOException("تعذر إزالة ملف بيانات الاختبار المؤقت.");repo=new LedgerRepository(context,session);result.putString("enrollment",repo.enroll().toString());}
   else{repo=new LedgerRepository(context,session);
    if(mode.equals("sync")){repo.sync();JSONObject view=repo.view();check("المحاكي يقرأ بيانات Supabase الأصلية",view.getJSONArray("contacts").length()==15&&view.getJSONArray("debts").length()==30&&view.getJSONArray("payments").length()==20);check("تحقق ترخيص الأيام السبعة الموقع",repo.canAddOffline());result.putString("scope",repo.journal.scope);}
    if(mode.equals("offline_prepare")){JSONObject view=repo.view(),debt=null;for(int i=0;i<view.getJSONArray("debts").length();i++){JSONObject d=view.getJSONArray("debts").getJSONObject(i);if(d.getLong("remainingCents")>=10000){debt=d;break;}}if(debt==null)throw new AssertionError("لا يوجد دين مناسب للاختبار.");JSONObject entry=repo.add("payment.create",new JSONObject().put("debtId",debt.getString("id")).put("amountCents",10000).put("method","cash").put("note","اختبار انقطاع العملية؛ سيلغى قبل الإرسال"));repo.journal.metadata("crash-test",new JSONObject().put("operationId",entry.getJSONObject("command").getString("operationId")).put("debtId",debt.getString("id")).put("expectedRemaining",debt.getLong("remainingCents")-10000));check("حفظ دفعة دون اتصال قبل نجاح الإجراء",repo.journal.entries().length()>0);}
    if(mode.equals("offline_verify")){JSONObject expected=repo.journal.metadata("crash-test"),view=repo.view();boolean found=false;for(int i=0;i<view.getJSONArray("debts").length();i++){JSONObject d=view.getJSONArray("debts").getJSONObject(i);if(d.getString("id").equals(expected.getString("debtId")))found=d.getLong("remainingCents")==expected.getLong("expectedRemaining");}check("دفعة معلقة ورصيدها بقيا بعد قتل العملية",found);repo.journal.cancel(expected.getString("operationId"));check("إلغاء الدفعة التي لم ترسل يحفظ تاريخها",repo.journal.entries().getJSONObject(repo.journal.entries().length()-1).getString("state").equals("cancelled"));}
   }
   result.putString("evidence",new JSONObject().put("mode",mode).put("tests",tests).toString());finish(0,result);
  }finally{if(repo!=null)repo.journal.close();}
 }
}
