package com.sadad.app;
import android.app.*; import android.content.Intent; import android.graphics.*; import android.os.Bundle; import android.view.*; import android.widget.*; import android.database.sqlite.SQLiteDatabase;
import org.json.*; import java.io.*; import java.lang.reflect.*;
public final class Ui253Instrumentation extends Instrumentation {
 MainActivity host; NativeScreens screens; File output;
 @Override public void onCreate(Bundle args){super.onCreate(args);start();}
 @Override public void onStart(){Bundle result=new Bundle();try{
  check(getTargetContext().getPackageName().contains(".qa"),"QA only");
  new SessionStore(getTargetContext()).save(new JSONObject().put("token","qa").put("expiresAt",Long.MAX_VALUE).put("deviceStaffName","رامي").put("account",new JSONObject().put("id","qa").put("name","متجر الاختبار").put("status","active").put("subscriptionMode","permanent")));
  host=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK)); Field field=MainActivity.class.getDeclaredField("screens");field.setAccessible(true);screens=(NativeScreens)field.get(host);output=new File(host.getFilesDir(),"qa253");output.mkdirs();
  runOnMainSync(()->{host.setTheme(false);host.saveStoreProfile("متجر الاختبار","أحمد");});
  Method operator=MainActivity.class.getDeclaredMethod("savedOfflineOperator",String.class);operator.setAccessible(true);String name=(String)operator.invoke(host,"رامي");check(name.equals(operator.invoke(host,"اسم جديد")),"First operator changed");
  migration();
  SQLiteDatabase db=host.database.getWritableDatabase();db.delete("payments",null,null);db.delete("debts",null,null);db.delete("contacts",null,null);
  long person=host.database.saveContact(new JSONObject().put("name","محمد").put("phone","0591111111")).getLong("id");host.database.saveDebt(new JSONObject().put("contactId",person).put("amount","1000").put("direction","receivable"));
  String[] methods={"cash","bank","wallet_jawwal","wallet_palpay"};for(int i=0;i<4;i++)host.database.savePayment(new JSONObject().put("contactId",person).put("amount",String.valueOf(11+i)).put("method",methods[i]).put("createdBy",host.currentOperatorName()));
  JSONArray payments=host.database.getSnapshot().getJSONArray("payments");check(payments.length()==4,"Methods not saved");for(int i=0;i<4;i++)check(payments.getJSONObject(i).getString("createdBy").equals("رامي"),"Operator lost");
  screens.contactId=person;show("payment_form");Spinner method=spinner(root());check(method!=null&&method.getCount()==4,"Payment choices");check(method.getItemAtPosition(2).equals("محفظة جوال")&&method.getItemAtPosition(3).equals("محفظة بال بي"),"Wallet labels");capture(root(),"payment-form");
  show("contact_detail");check(text(root(),"المدفوع")==null&&text(root(),"المتبقي")==null,"Crowded details");check(text(root(),"سجّلها: رامي")!=null,"Person ledger operator");capture(root(),"person-ledger");
  show("home");check(text(root(),"مرحبًا بك")!=null&&text(root(),"متجر الاختبار")!=null&&text(root(),"سجّلها: رامي")!=null,"Home greeting/operator");capture(root(),"home");
  show("contacts");check(text(root(),"متجر الاختبار")==null,"Header store badge remained");
  Bitmap image=Bitmap.createBitmap(400,200,Bitmap.Config.ARGB_8888);Canvas paint=new Canvas(image);paint.drawColor(Color.rgb(80,190,150));Paint blue=new Paint();blue.setColor(Color.rgb(20,100,210));paint.drawRect(200,0,400,200,blue);
  final ProfilePhotoEditor.CropView[] crop={null};runOnMainSync(()->{crop[0]=new ProfilePhotoEditor.CropView(host,image);crop[0].layout(0,0,200,200);crop[0].setZoom(3);crop[0].offsetX=99999;crop[0].offsetY=-99999;});Bitmap exported=crop[0].export();check(Color.alpha(exported.getPixel(0,0))==255&&Color.alpha(exported.getPixel(1023,1023))==255,"Crop empty border");exported.recycle();runOnMainSync(()->{crop[0].rotate();crop[0].center();});exported=crop[0].export();check(exported.getWidth()==1024&&crop[0].source.getWidth()==200,"Crop rotation");exported.recycle();crop[0].release();
  show("settings");final AlertDialog[] editor={null};runOnMainSync(()->editor[0]=ProfilePhotoEditor.show(host,image,host.sessions.syncAccountId()));waitForIdleSync();capture(editor[0].getWindow().getDecorView(),"photo-editor");runOnMainSync(()->editor[0].getButton(-1).performClick());waitForIdleSync();image.recycle();check(host.profilePhoto(true)!=null&&host.profilePhoto(false)!=null,"Shared portrait");capture(root(),"settings-light");
  runOnMainSync(()->host.setTheme(true));show("settings");capture(root(),"settings-dark");runOnMainSync(()->host.setTheme(false));show("login");check(text(root(),"دخول الزبون")==null,"Customer login visible");capture(root(),"login");show("customer_login");check(!host.currentRoute().startsWith("customer"),"Customer route accessible");
  result.putString("stream","PASS: old payment migration, four payment channels, first login operator and ledger/home display, compact details, hidden customer entry/header badge, greeting, photo crop/zoom/alignment/rotation/save and shared portrait\n");finish(-1,result);
 }catch(Throwable error){result.putString("stream","FAIL: "+android.util.Log.getStackTraceString(error));finish(0,result);}}
 void migration()throws Exception{String file="qa253-migration.db";getTargetContext().deleteDatabase(file);SadadDatabase fixture=new SadadDatabase(getTargetContext(),file);long id=fixture.saveContact(new JSONObject().put("name","قديم")).getLong("id");fixture.saveDebt(new JSONObject().put("contactId",id).put("amount","100").put("direction","receivable"));fixture.savePayment(new JSONObject().put("contactId",id).put("amount","25").put("method","cash").put("createdBy","موظف قديم"));SQLiteDatabase db=fixture.getWritableDatabase();db.execSQL("CREATE TABLE payments_old (id INTEGER PRIMARY KEY AUTOINCREMENT,debt_id INTEGER NOT NULL REFERENCES debts(id) ON DELETE CASCADE,amount_cents INTEGER NOT NULL,method TEXT CHECK(method IN ('cash','bank','wallet')),note TEXT NOT NULL,created_by TEXT NOT NULL,created_at INTEGER NOT NULL)");db.execSQL("INSERT INTO payments_old SELECT * FROM payments");db.execSQL("DROP TABLE payments");db.execSQL("ALTER TABLE payments_old RENAME TO payments");db.setVersion(5);fixture.close();fixture=new SadadDatabase(getTargetContext(),file);JSONObject snapshot=fixture.getSnapshot();check(snapshot.getJSONArray("payments").getJSONObject(0).getString("createdBy").equals("موظف قديم"),"Old payment lost");fixture.savePayment(new JSONObject().put("contactId",id).put("amount","5").put("method","wallet_palpay"));check(fixture.getSnapshot().getJSONObject("totals").getDouble("receivable")==70,"Migration balance");fixture.close();}
 View root(){return host.getWindow().getDecorView();}void show(String route){runOnMainSync(()->{host.show(route);host.refreshCurrentScreen();});waitForIdleSync();}
 TextView text(View view,String value){if(view instanceof TextView&&((TextView)view).getText().toString().contains(value))return (TextView)view;if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++){TextView found=text(((ViewGroup)view).getChildAt(i),value);if(found!=null)return found;}return null;}
 Spinner spinner(View view){if(view instanceof Spinner)return (Spinner)view;if(view instanceof ViewGroup)for(int i=0;i<((ViewGroup)view).getChildCount();i++){Spinner found=spinner(((ViewGroup)view).getChildAt(i));if(found!=null)return found;}return null;}
 void capture(View view,String name)throws Exception{waitForIdleSync();Thread.sleep(250);runOnMainSync(()->{Bitmap bitmap=Bitmap.createBitmap(view.getWidth(),view.getHeight(),Bitmap.Config.ARGB_8888);view.draw(new Canvas(bitmap));try(FileOutputStream stream=new FileOutputStream(new File(output,name+".png"))){bitmap.compress(Bitmap.CompressFormat.PNG,100,stream);}catch(Exception error){throw new RuntimeException(error);}bitmap.recycle();});}void check(boolean value,String message){if(!value)throw new AssertionError(message);}
}
