package com.sadad.app;

import android.content.Context;
import android.os.SystemClock;
import android.provider.Settings;
import org.json.*;
import java.security.*;
import java.security.spec.*;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.util.*;

final class LedgerRepository {
 final EncryptedJournal journal;final SessionStore sessions;final InstallationKey installation;final LedgerTransport transport;final Context context;
 LedgerRepository(Context context,SessionStore sessions)throws Exception{this.context=context.getApplicationContext();this.sessions=sessions;installation=new InstallationKey(context);transport=new LedgerTransport(sessions,installation);String jwt=sessions.auth().getString("accessToken");String user=new JSONObject(new String(InstallationKey.unb64(jwt.split("\\.")[1]),StandardCharsets.UTF_8)).getString("sub");String scope="vhftjmiltqfwmrszdtgf|"+sessions.account().getString("id")+"|"+user;journal=new EncryptedJournal(context,scope);}
 private int boot(){return Settings.Global.getInt(context.getContentResolver(),"boot_count",-1);}
 JSONObject enroll()throws Exception{JSONObject r=transport.signed("/mobile/v3/enroll","POST",new JSONObject().put("publicKey",installation.publicKey()),"").getJSONObject("result");journal.metadata("installation",r);return r;}
 private JSONObject leasePayload(JSONObject envelope)throws Exception{byte[] payload=InstallationKey.unb64(envelope.getString("payload"));JSONObject jwk=envelope.getJSONObject("publicKey");AlgorithmParameters params=AlgorithmParameters.getInstance("EC");params.init(new ECGenParameterSpec("secp256r1"));ECParameterSpec ec=params.getParameterSpec(ECParameterSpec.class);PublicKey key=KeyFactory.getInstance("EC").generatePublic(new ECPublicKeySpec(new ECPoint(new BigInteger(1,InstallationKey.unb64(jwk.getString("x"))),new BigInteger(1,InstallationKey.unb64(jwk.getString("y")))),ec));Signature verifier=Signature.getInstance("SHA256withECDSA");verifier.initVerify(key);verifier.update(payload);if(!verifier.verify(InstallationKey.rawToDer(InstallationKey.unb64(envelope.getString("signature")))))throw new GeneralSecurityException("ترخيص غير صالح.");JSONObject p=new JSONObject(new String(payload,StandardCharsets.UTF_8));if(!p.getString("projectRef").equals("vhftjmiltqfwmrszdtgf")||!p.getString("installationId").equals(installation.id())||!p.getString("userId").equals(journal.scope.split("\\|")[2])||!String.valueOf(p.getLong("storeId")).equals(sessions.account().getString("id")))throw new GeneralSecurityException("نطاق الترخيص غير مطابق.");return p;}
 private void renewLease()throws Exception{JSONObject lease=transport.signed("/mobile/v3/lease","POST",new JSONObject(),"").getJSONObject("lease");JSONObject payload=leasePayload(lease);if(payload.getLong("expiresAt")-payload.getLong("issuedAt")!=7*86400000L)throw new GeneralSecurityException("مدة ترخيص غير صالحة.");journal.metadata("lease",new JSONObject().put("envelope",lease).put("payload",payload).put("elapsed",SystemClock.elapsedRealtime()).put("wall",System.currentTimeMillis()).put("boot",boot()));}
 boolean canAddOffline()throws Exception{JSONObject lease=journal.metadata("lease");String blocked=journal.metadata("sync").optString("blockedCode","");if(Arrays.asList("installation_revoked","installation_or_session_revoked","store_suspended","password_change_required").contains(blocked))return false;if(!lease.has("payload")||lease.getInt("boot")!=boot()||boot()<0)return false;long elapsed=SystemClock.elapsedRealtime()-lease.getLong("elapsed");if(elapsed<0||System.currentTimeMillis()<lease.getLong("wall")-60000)return false;JSONObject p=lease.getJSONObject("payload");return p.getLong("issuedAt")+elapsed<p.getLong("expiresAt");}
 private static boolean projected(JSONObject e){String s=e.optString("state");return !(s.equals("confirmed")||s.equals("cancelled")||s.equals("rejected")||s.equals("reviewed"));}
 JSONObject view()throws Exception{
  JSONObject coherent=journal.exportPlain(),cache=coherent.getJSONObject("cache"),out=new JSONObject();JSONArray contacts=new JSONArray(cache.optJSONArray("contacts")==null?"[]":cache.getJSONArray("contacts").toString()),debts=new JSONArray(cache.optJSONArray("debts")==null?"[]":cache.getJSONArray("debts").toString()),payments=new JSONArray(cache.optJSONArray("payments")==null?"[]":cache.getJSONArray("payments").toString()),entries=coherent.getJSONArray("entries");
  Map<String,JSONObject> cMap=new LinkedHashMap<>(),dMap=new LinkedHashMap<>();Set<String> reversed=new HashSet<>();JSONArray reversals=cache.optJSONArray("reversals");if(reversals!=null)for(int i=0;i<reversals.length();i++)reversed.add(reversals.getJSONObject(i).getString("payment_id"));
  for(int i=0;i<contacts.length();i++)cMap.put(contacts.getJSONObject(i).getString("id"),contacts.getJSONObject(i));
  JSONArray balances=cache.optJSONArray("debtBalances");for(int i=0;i<debts.length();i++){JSONObject d=debts.getJSONObject(i);long amount=d.getLong("amount_cents"),paid=0,version=1;if(balances!=null)for(int j=0;j<balances.length();j++){JSONObject b=balances.getJSONObject(j);if(b.getString("debtId").equals(d.getString("id"))){amount=b.getLong("amountCents");paid=b.getLong("paidCents");version=b.getLong("version");break;}}else for(int j=0;j<payments.length();j++){JSONObject p=payments.getJSONObject(j);if(p.getString("debt_id").equals(d.getString("id"))&&!reversed.contains(p.getString("id")))paid+=p.getLong("amount_cents");}d.put("currentAmountCents",amount).put("confirmedRemainingCents",amount-paid).put("remainingCents",amount-paid).put("version",version);dMap.put(d.getString("id"),d);}
  Set<String> excluded=new HashSet<>();for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);if(e.getString("state").equals("rejected")||e.getString("state").equals("cancelled"))excluded.add(e.getJSONObject("command").getString("operationId"));}
  for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);if(!projected(e))continue;JSONObject cmd=e.getJSONObject("command"),p=cmd.getJSONObject("payload");boolean valid=true;JSONArray dependencies=cmd.optJSONArray("dependsOn");if(dependencies!=null)for(int j=0;j<dependencies.length();j++)if(excluded.contains(dependencies.getString(j)))valid=false;if(!valid){e.put("projectionExcluded",true);excluded.add(cmd.getString("operationId"));continue;}String type=cmd.getString("type"),id=cmd.getString("entityId");if(type.equals("contact.create")){JSONObject c=new JSONObject(p.toString()).put("id",id).put("pending",true).put("archived",false).put("version",1);cMap.put(id,c);}else if(type.equals("debt.create")){if(!cMap.containsKey(p.getString("contactId"))){e.put("projectionExcluded",true);continue;}JSONObject d=new JSONObject(p.toString()).put("id",id).put("contact_id",p.getString("contactId")).put("amount_cents",p.getLong("amountCents")).put("currentAmountCents",p.getLong("amountCents")).put("confirmedRemainingCents",0).put("remainingCents",p.getLong("amountCents")).put("version",1).put("pending",true);dMap.put(id,d);}else if(type.equals("payment.create")){JSONObject d=dMap.get(p.getString("debtId"));if(d==null||p.getLong("amountCents")>d.getLong("remainingCents")){e.put("projectionExcluded",true);continue;}d.put("remainingCents",d.getLong("remainingCents")-p.getLong("amountCents")).put("hasPending",true);payments.put(new JSONObject(p.toString()).put("id",id).put("debt_id",p.getString("debtId")).put("amount_cents",p.getLong("amountCents")).put("pending",true));}}
  contacts=new JSONArray();for(JSONObject c:cMap.values())contacts.put(c);debts=new JSONArray();BigInteger rec=BigInteger.ZERO,pay=BigInteger.ZERO,crec=BigInteger.ZERO,cpay=BigInteger.ZERO;for(JSONObject d:dMap.values()){debts.put(d);boolean payable=d.getString("direction").equals("payable");BigInteger remaining=BigInteger.valueOf(d.getLong("remainingCents")),confirmed=BigInteger.valueOf(d.getLong("confirmedRemainingCents"));if(payable){pay=pay.add(remaining);cpay=cpay.add(confirmed);}else{rec=rec.add(remaining);crec=crec.add(confirmed);}}
  return out.put("contacts",contacts).put("debts",debts).put("payments",payments).put("entries",entries).put("confirmedReceivableCents",crec.toString()).put("confirmedPayableCents",cpay.toString()).put("receivableCents",rec.toString()).put("payableCents",pay.toString()).put("sync",journal.metadata("sync")).put("canAdd",canAddOffline()).put("installation",journal.metadata("installation")).put("scope",journal.scope).put("cursor",cache.optLong("cursor"));
 }
 synchronized JSONObject add(String type,JSONObject payload)throws Exception{
  if(!Arrays.asList("contact.create","debt.create","payment.create").contains(type))throw new IllegalArgumentException("هذا الإجراء يحتاج اتصالًا.");if(!canAddOffline())throw new IllegalArgumentException("يلزم اتصال للتحقق قبل إضافة إدخال؛ بقي الطابور والبيانات محفوظين.");JSONObject v=view();JSONArray dependencies=new JSONArray();String reference=type.equals("debt.create")?payload.getString("contactId"):type.equals("payment.create")?payload.getString("debtId"):"";
  JSONArray entries=v.getJSONArray("entries");for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);if(projected(e)&&e.getJSONObject("command").getString("entityId").equals(reference))dependencies.put(e.getJSONObject("command").getString("operationId"));}
  if(type.equals("debt.create")||type.equals("payment.create")){String contactRef=reference;if(type.equals("payment.create")){for(int k=0;k<v.getJSONArray("debts").length();k++){JSONObject d=v.getJSONArray("debts").getJSONObject(k);if(d.getString("id").equals(reference))contactRef=d.getString("contact_id");}}boolean available=false;for(int k=0;k<v.getJSONArray("contacts").length();k++){JSONObject c=v.getJSONArray("contacts").getJSONObject(k);if(c.getString("id").equals(contactRef)&&!c.optBoolean("archived"))available=true;}if(!available)throw new IllegalArgumentException("الشخص غير متاح أو مؤرشف.");}if(type.equals("contact.create")){if(payload.optString("name").trim().isEmpty())throw new IllegalArgumentException("أدخل الاسم.");}else{long cents=payload.getLong("amountCents");if(cents<=0||cents>9007199254740991L||!String.valueOf(cents).equals(String.valueOf(payload.get("amountCents"))))throw new IllegalArgumentException("المبلغ يجب أن يكون سنتات صحيحة موجبة.");if(type.equals("payment.create")){boolean found=false;JSONArray debts=v.getJSONArray("debts");for(int i=0;i<debts.length();i++){JSONObject d=debts.getJSONObject(i);if(d.getString("id").equals(reference)){found=true;if(cents>d.getLong("remainingCents"))throw new IllegalArgumentException("الدفعة تتجاوز المتبقي بعد الإدخالات المعلقة.");}}if(!found)throw new IllegalArgumentException("الدين غير موجود.");}}
  JSONObject cmd=baseCommand(type,payload).put("dependsOn",dependencies);return journal.add(cmd);
 }
 private JSONObject baseCommand(String type,JSONObject payload)throws Exception{return new JSONObject().put("schemaVersion",1).put("operationId",UUID.randomUUID().toString()).put("entityId",UUID.randomUUID().toString()).put("type",type).put("originInstallationId",installation.id()).put("originGeneration",journal.metadata("installation").getInt("generation")).put("createdAt",new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX",java.util.Locale.ROOT).format(new Date())).put("dependsOn",new JSONArray()).put("expectedEpoch",journal.metadata("cache").getString("epoch")).put("payload",payload);}
 synchronized JSONObject online(String type,JSONObject payload,long version)throws Exception{JSONObject cmd=baseCommand(type,payload).put("expectedVersion",version);transport.signed("/mobile/v3/snapshot","GET",null,"");JSONObject entry=journal.add(cmd);entry=journal.startSend(cmd.getString("operationId"));try{JSONObject receipt=transport.signed("/mobile/v3/operations","POST",cmd,"").getJSONObject("result");entry.put("receipt",receipt);journal.state(entry,receipt.getString("status").equals("accepted")?"acknowledged":"rejected",receipt.optString("code"));sync();return receipt;}catch(Exception e){journal.state(entry,"uncertain",e.getMessage());throw e;}}
 synchronized void sync()throws Exception{
  String owner=journal.acquire();if(owner==null)return;
  try{JSONObject installationState=enroll();if(!installationState.getString("status").equals("active"))throw new IllegalArgumentException("طلب الجهاز ينتظر موافقة الإدارة.");renewLease();journal.merge(transport.signed("/mobile/v3/snapshot","GET",null,"").getJSONObject("snapshot"));if(journal.metadata("sync").optBoolean("recoveryRequired"))return;JSONArray entries=journal.entries();String permit=journal.metadata("recovery").optString("permitId","");
   for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);String state=e.getString("state");if(state.equals("confirmed")||state.equals("rejected")||state.equals("cancelled")||state.equals("reviewed"))continue;JSONObject cmd=e.getJSONObject("command");if(!cmd.getString("originInstallationId").equals(installation.id())&&permit.isEmpty()){journal.state(e,"blocked","يلزم تصريح استرداد من الإدارة للأصل القديم.");continue;}journal.renew(owner);e=journal.startSend(cmd.getString("operationId"));if(e==null)continue;
    try{JSONObject r=transport.signed("/mobile/v3/operations","POST",new JSONObject(e.getString("wire")),cmd.getString("originInstallationId").equals(installation.id())?"":permit).getJSONObject("result");e.put("receipt",r);journal.state(e,r.getString("status").equals("accepted")?"acknowledged":"rejected",r.optString("code",""));}
    catch(LedgerTransport.Failure f){journal.state(e,f.status==401||f.status==403?"blocked":"uncertain",f.getMessage());if(f.code.equals("dependency_pending"))continue;throw f;}catch(Exception error){journal.state(e,"uncertain",error.getMessage());throw error;}
   }
   journal.merge(transport.signed("/mobile/v3/snapshot","GET",null,"").getJSONObject("snapshot"));
  }catch(Exception error){journal.metadata("sync",journal.metadata("sync").put("error",error.getMessage()).put("blockedCode",error instanceof LedgerTransport.Failure?((LedgerTransport.Failure)error).code:"").put("at",System.currentTimeMillis()));throw error;}finally{journal.release(owner);}
 }
}
