-- Sadad hosted PostgreSQL schema for Supabase.
-- Application timestamps stay as epoch milliseconds to match the Android/API contract.

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text not null,
  salt text not null,
  password_hash text not null,
  force_password_change boolean not null default false,
  created_at bigint not null
);
create unique index if not exists admins_username_ci on public.admins (lower(username));

create table if not exists public.stores (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null,
  salt text not null,
  password_hash text not null,
  force_password_change boolean not null default true,
  status text not null default 'active' check (status in ('active','suspended','deleted')),
  suspend_until bigint,
  verified boolean not null default false,
  debtor_limit integer not null default 100 check (debtor_limit >= 0),
  subscription_mode text not null default 'permanent' check (subscription_mode in ('permanent','timed','paused')),
  subscription_started_at bigint,
  subscription_expires_at bigint,
  subscription_paused_remaining_ms bigint,
  allowed_devices integer not null default 1 check (allowed_devices between 1 and 50),
  permissions jsonb not null default '{}'::jsonb,
  whatsapp_enabled boolean not null default false,
  whatsapp_number_id text not null default '',
  whatsapp_token_enc text not null default '',
  whatsapp_template_name text not null default '',
  whatsapp_template_language text not null default 'ar',
  revision bigint not null default 0,
  created_at bigint not null
);
create unique index if not exists stores_username_ci on public.stores (lower(username));

create table if not exists public.sessions (
  token_hash text primary key,
  kind text not null check (kind in ('admin','store')),
  principal_id bigint not null,
  device_id text,
  expires_at bigint not null,
  created_at bigint not null
);
create index if not exists idx_sessions_expiry on public.sessions (expires_at);

create table if not exists public.login_rate_limits (
  bucket_key text primary key,
  failures integer not null,
  window_started_at bigint not null,
  blocked_until bigint not null default 0
);
create index if not exists idx_login_rate_limits_window on public.login_rate_limits (window_started_at);

create table if not exists public.store_devices (
  store_id bigint not null references public.stores(id) on delete cascade,
  device_id text not null,
  label text not null default '',
  first_seen_at bigint not null,
  last_seen_at bigint not null,
  revoked_at bigint,
  staff_name text not null default '',
  permissions jsonb not null default '{}'::jsonb,
  primary key (store_id, device_id)
);
create index if not exists idx_store_devices_active on public.store_devices (store_id, revoked_at);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  device_id text not null default '',
  actor text not null default '',
  action text not null,
  description text not null default '',
  created_at bigint not null
);
create index if not exists idx_audit_events_store_recent on public.audit_events (store_id, created_at desc, id desc);

create table if not exists public.store_backups (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  created_at bigint not null,
  reason text not null,
  snapshot_json jsonb not null,
  contact_count integer not null default 0,
  debt_count integer not null default 0,
  payment_count integer not null default 0
);
create index if not exists idx_store_backups_recent on public.store_backups (store_id, created_at desc, id desc);

create table if not exists public.contact_archives (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  contact_id bigint not null,
  contact_name text not null,
  archived_at bigint not null,
  source_revision bigint not null default 0,
  snapshot_json jsonb not null,
  debt_count integer not null default 0,
  payment_count integer not null default 0,
  restored_at bigint
);
create index if not exists idx_contact_archives_recent on public.contact_archives (store_id, archived_at desc, id desc);

create table if not exists public.contacts (
  store_id bigint not null references public.stores(id) on delete cascade,
  id bigint not null,
  name text not null,
  phone text not null default '',
  category text not null default '',
  note text not null default '',
  whatsapp_opt_in boolean not null default false,
  credit_limit_cents bigint not null default 0,
  created_by text not null default '',
  created_at bigint not null,
  primary key (store_id, id)
);
create index if not exists idx_contacts_store_name on public.contacts (store_id, lower(name));
create index if not exists idx_contacts_store_phone on public.contacts (store_id, phone);

create table if not exists public.debts (
  store_id bigint not null,
  id bigint not null,
  contact_id bigint not null,
  direction text not null check (direction in ('receivable','payable')),
  amount_cents bigint not null check (amount_cents > 0),
  note text not null default '',
  due_date text not null default '',
  created_by text not null default '',
  created_at bigint not null,
  primary key (store_id, id),
  foreign key (store_id) references public.stores(id) on delete cascade,
  foreign key (store_id, contact_id) references public.contacts(store_id, id) on delete cascade
);
create index if not exists idx_debts_store_contact on public.debts (store_id, contact_id);
create index if not exists idx_debts_store_recent on public.debts (store_id, created_at desc, id desc);

create table if not exists public.payments (
  store_id bigint not null,
  id bigint not null,
  debt_id bigint not null,
  amount_cents bigint not null check (amount_cents > 0),
  method text not null default 'cash' check (method in ('cash','bank','wallet')),
  note text not null default '',
  created_by text not null default '',
  created_at bigint not null,
  server_received_at bigint not null default 0,
  primary key (store_id, id),
  foreign key (store_id) references public.stores(id) on delete cascade,
  foreign key (store_id, debt_id) references public.debts(store_id, id) on delete cascade
);
create index if not exists idx_payments_store_debt on public.payments (store_id, debt_id);
create index if not exists idx_payments_store_received on public.payments (store_id, server_received_at);

-- Keep all business tables private to the trusted API. Never expose the service-role key in Android.
alter table public.admins enable row level security;
alter table public.stores enable row level security;
alter table public.sessions enable row level security;
alter table public.login_rate_limits enable row level security;
alter table public.store_devices enable row level security;
alter table public.audit_events enable row level security;
alter table public.store_backups enable row level security;
alter table public.contact_archives enable row level security;
alter table public.contacts enable row level security;
alter table public.debts enable row level security;
alter table public.payments enable row level security;

revoke all on public.admins, public.stores, public.sessions, public.login_rate_limits,
  public.store_devices, public.audit_events, public.store_backups, public.contact_archives,
  public.contacts, public.debts, public.payments from anon, authenticated;
grant all on public.admins, public.stores, public.sessions, public.login_rate_limits,
  public.store_devices, public.audit_events, public.store_backups, public.contact_archives,
  public.contacts, public.debts, public.payments to service_role;
grant usage, select on all sequences in schema public to service_role;
